version: "3"
services:
  mongodb:
    image: index.docker.io/durancai/local-http-durancdb:latest
    container_name: duranc_db
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - db_data:/data/db
      - data:/tmp/share
    environment:
        DB_IP: "18.19.0.4"
        TZ: Asia/Kolkata
    command: mongod
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.4

  portal:
    image: index.docker.io/durancai/local-http-portal:latest
    container_name: duranc_portal
    depends_on:
      - mongodb
    ports:
       - 80:80
       - 83:83
       - 3000:3000
       - 3014:3004
       - 3005:3005
    restart: unless-stopped
    command: /bin/bash -c "/tmp/start.sh.x && exec /usr/bin/supervisord"
    volumes:
      - portal_data:/persistent:rw
      - portal_storage:/local_storage:rw
      - data:/tmp/share:rw
    environment:
        PORTAL_URL
        WIKI_ADMIN_EMAIL: img@duranc.com
        TZ: Asia/Kolkata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.5
   
  messenger:
    image: index.docker.io/durancai/local-http-messenger:latest
    container_name: duranc_messenger
    depends_on:
      - mongodb
      - portal
    ports:
        - 81:81
        - 3001:3001
    restart: unless-stopped
    volumes:
      - messenger_data:/persistent:rw
      - portal_storage:/local_storage:rw
    environment:
        TZ: Asia/Kolkata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.6

  streamer:
    image: index.docker.io/durancai/local-http-streamer:latest
    container_name: duranc_streamer
    depends_on:
      - mongodb
      - portal
      - messenger
    ports:
        - 82:82
        - 1935:1935
        - 3002:3002
        - 8554:8554
        - 8888:8888
    restart: unless-stopped
    volumes:
      - streamer_data:/persistent:rw
    environment:
        TZ: Asia/Kolkata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.7

  archiver:
    image: index.docker.io/durancai/local-http-archiver:latest
    container_name: duranc_archiver
    depends_on:
      - mongodb
      - portal
      - messenger
      - streamer
    ports:
       - 84:84
       - 3003:3003
       - 3004:3004
    restart: unless-stopped
    #command: /bin/bash -c "/tmp/start.sh.x && exec /usr/bin/supervisord"
    volumes:
      - archiver_data:/persistent:rw
      - portal_storage:/local_storage:rw
    environment:
        TZ: Asia/Kolkata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.105

  recorder:
    image: index.docker.io/durancai/local-http-recorder:latest
    container_name: duranc_recorder
    depends_on:
      - mongodb
      - portal
      - messenger
      - streamer
      - archiver
    restart: unless-stopped
    volumes:
      - recorder:/root/.duranc:rw
      - recorder:/persistent:rw
      - motion:/root/.motion:rw
    environment:
        TZ: Asia/Kolkata
    network_mode: host
    privileged: true
    # ports:
      # - 8081:8080
    command: /usr/bin/supervisord
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    # networks:
      # duranc-network:
        # ipv4_address: 18.19.0.9

  autoupdater:
    image: containrrr/watchtower
    container_name: duranc_autoupdater
    depends_on:
      - mongodb
      - portal
      - messenger
      - streamer
      - archiver
      - recorder
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/auth.json:/config.json:ro
    environment:
        TZ: Asia/Kolkata
    ports:
      - 9080:8080
    command: watchtower duranc_db duranc_portal duranc_messenger duranc_streamer duranc_archiver duranc_recorder -i 300 --cleanup --debug
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.10

volumes:
  db_data:
    external:
      name: http-duranc-db
  data:
    external:
      name: http-duranc-data
  portal_data:
    external:
      name: http-duranc-portal
  portal_storage:
    external:
      name: http-duranc-storage
  messenger_data:
    external:
      name: http-duranc-messenger
  streamer_data:
    external:
      name: http-duranc-streamer
  archiver_data:
    external:
      name: http-duranc-archiver
  recorder:
    external:
      name: http-rec-files
  motion:
    external:
      name: http-rec-motion-files

networks:
  duranc-network:
    external: true
