version: "3"
services:
  gateway:
    image: index.docker.io/durancai/staging-gateway-jetson:latest
    container_name: duranc_gateway
    restart: unless-stopped
    shm_size: "4gb"
    volumes:
      - gateway:/root/.duranc:rw
      - motion:/root/.motion:rw
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: /usr/bin/supervisord

  autoupdater:
    image: containrrr/watchtower
    container_name: duranc_autoupdater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/auth.json:/config.json:ro
    ports:
      - 9080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: watchtower duranc_gateway --schedule "0 0 0 * * *" --cleanup --debug

volumes:
  gateway:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /local-storage/gw-files/
  motion:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /local-storage/motion-files/

