version: "3"
services:
  gateway:
    image: index.docker.io/durancai/edge-ai-trial-gw:latest
    container_name: duranc_gateway
    restart: unless-stopped
    volumes:
      - gateway:/root/.duranc:rw
      - motion:/root/.motion:rw
    ports: 
      - 8080:8080
    command: /usr/bin/supervisord

  autoupdater:
    image: containrrr/watchtower
    container_name: duranc_autoupdater
    restart: unless-stopped
    environment:
      - REPO_USER: durancinc
      - REPO_PASS: dc202f88-e9d2-4e68-896b-95a55b08a0e3
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:8080
    command: watchtower duranc_gateway --interval 300 --cleanup --debug
volumes:
  gateway:
    external:
      name: edge-ai-gw-files
  motion:
    external:
      name: edge-ai-motion-files
