version: "3"
services:
   mongodb:
     build: ./docker-durancdb/
     image: duranc_database
     ports:
      - 27017:27017
     restart: unless-stopped
     volumes:
      - db_data:/data/db
     container_name: duranc_db
     command: mongod
     networks:
      duranc-network:
        ipv4_address: 18.19.0.4

   portal:
     depends_on:
        - mongodb
     build: ./docker-portal
     args:
        PORTAL_URL: dockerssl.duranc.com
     image: duranc_portal
     ports:
       - 3000:3000
     restart: unless-stopped
     volumes:
      - portal_data:/var/www/duranc
     environment:
        DEFAULT_HOST: dockerssl.duranc.com
        WIKI_ADMIN_EMAIL: img@duranc.com
        VIRTUAL_HOST: dockerssl.duranc.com
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: dockerssl.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_portal
     networks:
      duranc-network:
        ipv4_address: 18.19.0.5
   
   messenger:
     depends_on:
        - mongodb
        - portal
     build: ./docker-messenger
     image: duranc_messenger
     ports:
        - 3001:3001
     restart: unless-stopped
     volumes:
      - messenger_data:/var/www/duranc
     environment:
        VIRTUAL_HOST: dockermsg.duranc.com
        VIRTUAL_PORT: 3001
        LETSENCRYPT_HOST: dockermsg.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_messenger
     networks:
      duranc-network:
        ipv4_address: 18.19.0.6

   streamer:
     depends_on:
        - mongodb
        - portal
        - messenger
     build: ./docker-streamer
     image: duranc_streamer
     ports:
        - 3002:3002
     restart: unless-stopped
     volumes:
      - streamer_data:/var/www/duranc
      - /var/lib/docker/volumes/html-files/_data:/var/www/duranc/duranc-streamer/public:ro
     environment:
        VIRTUAL_HOST: dockerstr.duranc.com
        VIRTUAL_PORT: 3002
        LETSENCRYPT_HOST: dockerstr.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_streamer
     networks:
      duranc-network:
        ipv4_address: 18.19.0.7

volumes:
  db_data:
    external:
      name: duranc-db
  portal_data:
    external:
      name: duranc-portal
  messenger_data:
    external:
      name: duranc-messenger
  streamer_data:
    external:
      name: duranc-streamer

networks:
  duranc-network:
    external: true
